' Developer Express Code Central Example:
' How to remove standard bar items and add custom ones to the DocumentPreview toolbar
' 
' This example demonstrates how to customize the DocumentPreview control's
' toolbar.
' 
' In particular, it shows how you can remove a standard button from
' it, and add custom ones.
' 
' You can tie your custom logic to a button either in
' the BarManager.ItemClick event handler, or using the View Model commands.
' 
' See
' Also:
' http://www.devexpress.com/scid=E4482
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2974

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
