// Developer Express Code Central Example:
// How to remove standard bar items and add custom ones to the DocumentPreview toolbar
// 
// This example demonstrates how to customize the DocumentPreview control's
// toolbar.
// 
// In particular, it shows how you can remove a standard button from
// it, and add custom ones.
// 
// You can tie your custom logic to a button either in
// the BarManager.ItemClick event handler, or using the View Model commands.
// 
// See
// Also:
// http://www.devexpress.com/scid=E4482
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E2974

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolbarWPF.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
